export const ACTION_TYPES = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  FETCH_ALL: "FETCH_ALL",
  LOG_IN: "LOG_IN",
  ALREADY_LOGGED_IN: "ALREADY_LOGGED_IN",
  LOG_OUT: "LOG_OUT",
  CREATE_USER: "CREATE_USER",
};
