export const ACTION_TYPES = {
  // Posts
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  FETCH_ALL_POSTS: "FETCH_ALL_POSTS",
  FETCH__POSTS_FOR_ME: "FETCH__POSTS_FOR_ME",
  // LoggedInUser
  LOG_IN: "LOG_IN",
  ALREADY_LOGGED_IN: "ALREADY_LOGGED_IN",
  LOG_OUT: "LOG_OUT",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  // Friendships
  GET_MY_FRIENDS: "GET_MY_FRIENDS",
  ADD_FRIEND: "ADD_FRIEND",
  DELETE_FRIEND: "DELETE_FRIEND",
};
